com.fasterxml.jackson.*:* = 2.21.4
com.fasterxml.jackson.core:jackson-annotations = 2.21
com.netflix.nebula:nebula-test = 12.1.0
com.palantir.gradle.plugintesting:gradle-plugin-testing-junit = 0.69.0
junit:junit = 4.13.2
org.junit.jupiter:* = 6.1.2
org.junit.vintage:* = 6.1.2
org.junit.platform:* = 6.1.2
org.immutables:value = 2.12.2
org.spockframework:* = 2.4-groovy-4.0
