com.fasterxml.jackson.*:* = 2.21.1
com.fasterxml.jackson.core:jackson-annotations = 2.21
com.netflix.nebula:nebula-test = 10.6.2
com.palantir.gradle.plugintesting:gradle-plugin-testing-junit = 0.66.0
junit:junit = 4.13.2
org.junit.jupiter:* = 6.0.3
org.junit.vintage:* = 6.0.3
org.junit.platform:* = 6.0.3
org.immutables:value = 2.12.1
